  language: python
  python:
    #- "3.6"
    - "2.7"
  os:
  - linux
  before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  addons:
    apt:
      packages:
        - google-chrome-stable
  install:
    - pip install -r requirements.txt
  script:
    - py.test
