  dist: trusty
  sudo: required
  language: python
  python:
    #- "3.6"
    - "2.7"
  os:
  - linux
  addons:
    apt:
      sources:
       - google-chrome
      packages:
       - google-chrome-stable fluxbox

  before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - fluxbox >/dev/null 2>&1 &
  install:
  - pip install -r requirements.txt
  script:
    - py.test
